# Go generate the sha-hash run
# HASH=$(openssl sha256  das2py-${VERSION}.tar.gz | awk '{print $2}')
#
# Example:
#  openssl sha256 das2py-tmp.tar.gz | awk '{print $2}'

{% set name = "das2py" %}
{% set das2c_version = "3.0.3" %}
{% set conda_version = "3.0.4" %}
{% set bld_date = "20250206" %}

{% set das2py_url = "https://github.com/das-developers/das2py/archive/refs/tags/v3.0-pre4.tar.gz" %}
{% set das2py_sha = "85a75f98ef962845b9a62fe7bb4321b4c37d58e660c93f5a0b876a24831412e8" %}

#{% set das2py_url = "https://space.physics.uiowa.edu/~pikerc/das2py-tmp.tar.gz" %}
#{% set das2py_sha = "7ad32aa81ef052d572f05b0e087b71e1d3e8612bc0f3692172517c88f2fb1a29" %}

package:
   name: {{ name }} 
   version: {{ conda_version }} 
   
source:
   url: {{ das2py_url }}
   sha256: {{ das2py_sha }}
   
build:
   # This is the zeroth build
   number: 0
   
# The build process for das2py calls python in the make files so we
# need to make sure it uses the anaconda python, not the system version

requirements:
   build:
      - {{ compiler('c') }}
      - setuptools
      - python
      - pip
      - wheel
      - numpy >=1.10.0 
      - das2c =={{ das2c_version }}
      - lxml
      - expat
      - fftw
      - openssl
      - pthreads4w ==3.0.1 # [ win ]


   host:
      - python
      - numpy >=1.10.0
      - das2c =={{ das2c_version }}
      - lxml

   run:
      - python
      - setuptools
      - numpy >=1.10.0
      - nomkl [ osx and x86_64 ]
      - lxml
      - das2c =={{ das2c_version }}

      
test:
   imports:
      - das2
      - _das2
   source_files:
      - test/TestRead.py
      - test/test_read_empty.d2s
      - test/TestDasTime.py
      - test/TestCatalog.py
      - test/TestSortMinimal.py
      - test/ex08_dynaspec_namespace.d3t
      - test/ex05_waveform_extra.d3t
      - test/ex06_waveform_binary.d3b
      - test/ex08_dynaspec_namespace.d3t
      - test/ex12_sounder_xyz.d3t
      - test/ex13_object_annotation.d3t
      - test/ex14_object_tfcat.d3t
      - test/ex15_vector_frame.d3b
      - test/ex16_mag_grid_doc.d3x
      - test/ex96_yscan_multispec.d2t
   commands:
      - python test/TestRead.py
      - python test/TestDasTime.py
      - python test/TestCatalog.py
      - python test/TestSortMinimal.py
      - das_verify test/ex05_waveform_extra.d3t
      - das_verify test/ex06_waveform_binary.d3b
      - das_verify test/ex08_dynaspec_namespace.d3t
      - das_verify test/ex12_sounder_xyz.d3t
      - das_verify test/ex13_object_annotation.d3t
      - das_verify test/ex14_object_tfcat.d3t
      - das_verify test/ex15_vector_frame.d3b
      - das_verify test/ex16_mag_grid_doc.d3x
      - das_verify test/ex96_yscan_multispec.d2t

about:
   home: https://das2.org/das2py
   license: MIT
   summary: An efficient space physics data client for python
