# To upload this file after building...
#
# anaconda login
# cd \programdata\miniconda3\conda-bld\win-64
# anaconda upload -u dasdevelopers pthreads4w-3.0.0-hfa6e2cd_0.tar.bz2
#
# To use this package
# conda install -c dasdevelopers pthreads4w



{% set name = "pthreads4w" %}
{% set version = "3.0.1" %}

#{% set ptw_url "http://das2.org/das2py/files/pthreads4w-{{ version }}.tar.gz" %}
#{% set ptw_sha = "b86741aa1c4600905ed3cb642269225f9ccee17c864e8b2448f730c3680c1966" %}
{% set ptw_url = "https://downloads.sourceforge.net/project/pthreads4w/pthreads4w-code-v3.0.0.zip" %}
{% set ptw_sha = "b81136effb7185c77601fe2e0e6ac19bd996912e4814cebdd3010b0fac9e259b" %}

package:
   name: {{ name }} 
   version: {{ version }} 
   
source:
   #folder: pthreads4w
   url: {{ ptw_url }}
   sha256: {{ ptw_sha }}
   patches:
      - 0001_change_install_dest.patch # update the makefile
   
build:
   # This is the zeroth build
   number: 0
   
test:
   commands:
      - if not exist %PREFIX%\include\pthread.h exit 1
      - if not exist %PREFIX%\bin\pthreadVC3.dll exit 1
      - if not exist %PREFIX%\lib\pthreadVC3.lib exit 1
      - if not exist %PREFIX%\bin\pthreadVC3d.dll exit 1
      - if not exist %PREFIX%\lib\pthreadVC3d.lib exit 1
      - if not exist %PREFIX%\lib\libpthreadVC3.lib exit 1
      - if not exist %PREFIX%\lib\libpthreadVC3d.lib exit 1

about:
   home: https://sourceforge.net/projects/pthreads4w/
   license: APACHE
   license_file: LICENSE
   summary: An implementation of the POSIX threads API for Windows
   
requirements:
   build:
      - {{ compiler('c') }}
                  
